name-template: "$NEXT_PATCH_VERSION 🌈"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "Breaking changes:"
    labels:
      - "breaking change"
  - title: "⬆️ Dependencies"
    collapse-after: 1
    labels:
      - "dependencies"
template: |
  ## Merged pull requests:

  $CHANGES
