name: Generate changelog

on:
  release:
    types: [published]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for default branch
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release_branch: master

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          base: master
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update changelog
          title: Update changelog
          body: Update the changelog. This PR is created automatically after a new release.
          branch: update-changelog
